export const exerciciosPorTreino = {
  Treino_Abdomen_Biceps: [
    { nome: "Abdominal Canivete", videoUrl: "/Treino_Abdomen/Abdominal_canivete.mp4" },
    { nome: "Abdominal supra", videoUrl: "/Treino_Abdomen/Abdominal supra.mp4" },
    { nome: "Prancha com flexão de ombro", videoUrl: "/Treino_Abdomen/Prancha com flexão de ombro.mp4" },
    { nome: "Rosca bíceps alternada com pegada em rotação", videoUrl: "/Treino_Bicpes/Rosca bíceps alternada com pegada em rotação.mp4" },
    { nome: "Rosca bíceps com barra", videoUrl: "/Treino_Bicpes/Rosca bíceps com barra.mp4" },
    { nome: "Rosca bíceps concentrado com halter", videoUrl: "/Treino_Bicpes/Rosca bíceps concentrado com halter.mp4" },
    { nome: "Rosca bíceps no banco inclinado", videoUrl: "/Treino_Bicpes/Rosca bíceps no banco inclinado.mp4" },
  ],
  Treino_Costas_Triceps: [
    { nome: "Pulldown na polia com barra", videoUrl: "/Treino_Costas/Pulldown na polia com barra.mp4" },
    { nome: "Puxada aberta com pegada pronada", videoUrl: "/Treino_Costas/Puxada aberta com pegada pronada.mp4" },
    { nome: "Remada curvada com halteres", videoUrl: "/Treino_Costas/Remada curvada com halteres.mp4" },
    { nome: "Triceps francês com halter", videoUrl: "/Treino_Triceps/Tríceps francês com halter.mp4" },
    { nome: "Triceps na paralela", videoUrl: "/Treino_Triceps/Tríceps na paralela.mp4" },
    { nome: "Triceps na polia com barra reta", videoUrl: "/Treino_Triceps/Tríceps na polia com barra reta.mp4" },
    { nome: "Triceps testa com barra", videoUrl: "/Treino_Triceps/Tríceps testa com barra.mp4" },
  ],
  Treino_Peito_Ombro: [
    { nome: "Supino reto com barra livre", videoUrl: "/Treino_Peito/Supino reto com barra livre.mp4" },
    { nome: "Supino inclinado com halteres", videoUrl: "/Treino_Peito/Supino inclinado com halteres.mp4" },
    { nome: "Crucifixo na máquina", videoUrl: "/Treino_Peito/Crucifixo na máquina.mp4" },
    { nome: "Desenvolvimento com barra", videoUrl: "/Treino_Ombro/Desenvolvimento com barra.mp4" },
    { nome: "Desenvolvimento com halteres em pé", videoUrl: "/Treino_Ombro/Desenvolvimento com halteres em pé.mp4" },
    { nome: "Elevação lateral com halteres em pé", videoUrl: "/Treino_Ombro/Elevação lateral com halteres em pé.mp4" },
    { nome: "Remada alta com barra", videoUrl: "/Treino_Ombro/Remada alta com barra.mp4" },
  ],
  Treino_Pernas_Abdomen: [
    { nome: "Agachamento com abdução de quadril com elástico", videoUrl: "/Treino_Pernas/Agachamento com abdução de quadril com elástico.mp4" },
    { nome: "Leg press 45º", videoUrl: "/Treino_Pernas/Leg press 45º.mp4" },
    { nome: "Cadeira extensora", videoUrl: "/Treino_Pernas/Cadeira extensora.mp4" },
    { nome: "Mesa flexora", videoUrl: "/Treino_Pernas/Mesa flexora.mp4" },
    { nome: "Elevação pélvica na máquina", videoUrl: "/Treino_Pernas/Elevação pélvica na máquina.mp4" },
    { nome: "Abdominal infra no solo", videoUrl: "/Treino_Abdomen/Abdominal infra no solo.mp4" },
    { nome: "Prancha lateral com abdução de quadril", videoUrl: "/Treino_Abdomen/Prancha lateral com abdução de quadril.mp4" },
  ],
};